apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: default
type: Opaque
data:
  # admin@4thitek.com (base64 encoded)
  PGADMIN_DEFAULT_EMAIL: YWRtaW5ANHR0aGl0ZWsuY29t
  # Strong-P@ssw0rd-2024! (base64 encoded)
  PGADMIN_DEFAULT_PASSWORD: U3Ryb25nLVBAc3N3MHJkLTIwMjQh