apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "4thitek PostgreSQL",
          "Group": "Servers",
          "Host": "postgres-service",
          "Port": 5432,
          "MaintenanceDB": "4thitek_db",
          "Username": "postgres",
          "PassFile": "/pgpass",
          "SSLMode": "prefer",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
        }
      }
    }
  # pgpass moved to secret for security