apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      nodeSelector:
        kubernetes.io/hostname: multinode-demo-m02
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:8.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_PASSWORD
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        securityContext:
          runAsNonRoot: true
          runAsUser: 5050
          runAsGroup: 5050
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: pgadmin-config
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
        - name: pgadmin-pgpass
          mountPath: /pgpass
          subPath: pgpass
      volumes:
      - name: pgadmin-config
        configMap:
          name: pgadmin-config
          defaultMode: 0644
      - name: pgadmin-pgpass
        secret:
          secretName: pgadmin-pgpass-secret
          defaultMode: 0600