apiVersion: v1
kind: Service
metadata:
  name: fe-main-service
  labels:
    app: fe-main
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: fe-main
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fe-main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: main.4thitek.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fe-main-service
            port:
              number: 3000