apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # postgres123 (base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  # postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  # 4thitek_db (base64 encoded)
  POSTGRES_DB: NHRoaXRla19kYg==