apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # PostgreSQL-Strong-P@ss2024! (base64 encoded)
  POSTGRES_PASSWORD: UG9zdGdyZVNRTC1TdHJvbmctUEBzczIwMjQh
  # postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  # 4thitek_db (base64 encoded)
  POSTGRES_DB: NHRoaXRla19kYg==