apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-secret
  namespace: kafka
type: Opaque
data:
  # admin (base64 encoded)
  SPRING_SECURITY_USER_NAME: YWRtaW4=
  # Kafka-Admin-2024! (base64 encoded)
  SPRING_SECURITY_USER_PASSWORD: S2Fma2EtQWRtaW4tMjAyNCE=