apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv-3
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/kafka-3/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv-4
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/kafka-4/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv-5
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/kafka-5/data