apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-dealer
  labels:
    app: fe-dealer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-dealer
  template:
    metadata:
      labels:
        app: fe-dealer
    spec:
      nodeSelector:
        kubernetes.io/hostname: multinode-demo
      containers:
      - name: fe-dealer
        image: fe-dealer:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5