apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-admin
  labels:
    app: fe-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-admin
  template:
    metadata:
      labels:
        app: fe-admin
    spec:
      nodeSelector:
        kubernetes.io/hostname: multinode-demo
      containers:
      - name: fe-admin
        image: fe-admin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5