apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: default
  labels:
    app: pgbouncer
data:
  pgbouncer.ini: |
    [databases]
    # Main database for all services
    4thitek_db = host=postgres-service port=5432 dbname=4thitek_db pool_size=12
    
    # Legacy aliases for backward compatibility (optional)
    main_db = host=postgres-service port=5432 dbname=4thitek_db pool_size=12
    admin_db = host=postgres-service port=5432 dbname=4thitek_db pool_size=9
    dealer_db = host=postgres-service port=5432 dbname=4thitek_db pool_size=9
    
    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 5432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    
    # Connection pooling
    pool_mode = transaction
    max_client_conn = 100
    default_pool_size = 30
    min_pool_size = 5
    
    # Timeouts
    server_connect_timeout = 15
    server_login_retry = 15
    query_timeout = 0
    query_wait_timeout = 120
    client_idle_timeout = 0
    client_login_timeout = 60
    autodb_idle_timeout = 3600
    
    # Logging
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    
    # Security
    ignore_startup_parameters = extra_float_digits
    
    # Admin
    admin_users = postgres
    stats_users = postgres
    
  userlist.txt: |
    # Format: "username" "password_hash"
    # MD5 hash of password "SecureP@ssw0rd2024postgres": md5(password + username)
    "postgres" "md595be92e919fc9b59aab83c4081749544"