apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: default
  labels:
    app: pgbouncer
    tier: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
        tier: database
    spec:
      nodeSelector:
        kubernetes.io/hostname: multinode-demo-m02
      containers:
      - name: pgbouncer
        image: pgbouncer/pgbouncer:latest
        ports:
        - containerPort: 6432
          name: pgbouncer
        securityContext:
          runAsNonRoot: true
          runAsUser: 70
          runAsGroup: 70
          allowPrivilegeEscalation: false
        env:
        - name: DATABASES_HOST
          value: "postgres-service"
        - name: DATABASES_PORT
          value: "5432"
        - name: DATABASES_USER
          valueFrom:
            secretKeyRef:
              name: pgbouncer-secret
              key: PGBOUNCER_AUTH_USER
        - name: DATABASES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgbouncer-secret
              key: PGBOUNCER_AUTH_PASSWORD
        volumeMounts:
        - name: pgbouncer-config
          mountPath: /config
          readOnly: true
        command: ["/bin/sh"]
        args: 
          - -c
          - |
            cp /config/* /etc/pgbouncer/
            exec /opt/pgbouncer/entrypoint.sh
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 6432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 6432
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: pgbouncer-config
        configMap:
          name: pgbouncer-config
          items:
          - key: pgbouncer.ini
            path: pgbouncer.ini
          - key: userlist.txt
            path: userlist.txt
      restartPolicy: Always
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pgbouncer